
package robotbuilder.actions;

import java.awt.event.ActionEvent;
import java.io.IOException;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.JOptionPane;
import robotbuilder.MainFrame;
import robotbuilder.exporters.ExportFile;
/**
 *
 * @author alex. Modified by SomeNerd
 */
public class CleanUpAction extends AbstractAction {

    public CleanUpAction() {
        putValue(Action.NAME, "Clean Up");
        putValue(Action.SHORT_DESCRIPTION, "Gets rid of any autogenerated comments from your code.\nYou cannot edit your file from RobotBuilder if you do this.");
    }

    @Override
    public void actionPerformed(ActionEvent ae) {
    	/* Plan
    	 * Find a way to look at the exported projects and search for the comments (Should be found in where RobotBuilder imports exported code from)
    	 * Simply removes the EXACT LITERAL string of the autogenerated code. That way if the user had put any of their own comments after the text, that will be unaffected
    	 * Also, this should check if that is the case and then place and extra "//" before said text just in case and THEN remove the string
    	 */
    	
    	
    	
        JOptionPane.showMessageDialog(MainFrame.getInstance(),
                "Verbose Cleaning Starts once you click \"OK\"",
                "Yay!", JOptionPane.INFORMATION_MESSAGE);
        
        //Prompt after each action
        String file;
        	file = new ExportFile().getExport();
        	
        
        JOptionPane.showMessageDialog(MainFrame.getInstance(),
                "PATH DETECTED:\n" + file,
                "Yay!", JOptionPane.INFORMATION_MESSAGE);

        //{Code to detect path} If not detected, say "You have to export some code first" and return. If detected, load file into an array
        
        JOptionPane.showMessageDialog(MainFrame.getInstance(),
                "This TextBox appeared successfully",
                "Yay!", JOptionPane.INFORMATION_MESSAGE);
        
        //Look at each line for the double slashes and //BEGIN AUTOGENERATED CODE
        //Just remove the whole line and eventually find the length of the string based on the length of the word after "ID=%id" plus the length of the string
        
        JOptionPane.showMessageDialog(MainFrame.getInstance(),
                "This TextBox appeared successfully",
                "Yay!", JOptionPane.INFORMATION_MESSAGE);
        
        //Rewrite the file
        
        JOptionPane.showMessageDialog(MainFrame.getInstance(),
                "This TextBox appeared successfully",
                "Yay!", JOptionPane.INFORMATION_MESSAGE);
        
        //Eventually do a foreach loop for all files that are exported. For now, however, just focus on the Subsystem
        
    	
        
        
    	/* BEGIN CODE OF VERIFY CODE, MAINLY FOR THE POP-UP
        String message = MainFrame.getInstance().getCurrentRobotTree().getRoot().getErrorMessage();

        if (message.equals("")) {
            JOptionPane.showMessageDialog(MainFrame.getInstance(),
                    "Your robot is valid and ready to export.",
                    "Valid Robot", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(MainFrame.getInstance(),
                    message, "Invalid Robot", JOptionPane.ERROR_MESSAGE);
        }
        */
    }

}
